// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2023 SAP SE.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DomainInitParameters struct {

	// Domain part of full domain name. If specified the sub_domain argument needs to be provided and the name will be computed.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// Flag that sets the domain as an internal domain. Internal domains are used for internal app to app networking only. Defaults to "false". Only works on shared domain.
	// Flag that sets the domain as an internal domain. Internal domains are used for internal app to app networking only.
	Internal *bool `json:"internal,omitempty" tf:"internal,omitempty"`

	// Full name of domain. If specified then the sub_domain and domain attributes will be computed from the name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the Org that owns this domain. If specified, this resource will provision a private domain. By default, the provisioned domain is a public (shared) domain.
	// +crossplane:generate:reference:type=github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/apis/organization/v1alpha1.Organization
	// +crossplane:generate:reference:extractor=github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/config.ExternalID()
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Reference to a Organization in organization to populate org.
	// +kubebuilder:validation:Optional
	OrgRef *v1.Reference `json:"orgRef,omitempty" tf:"-"`

	// Selector for a Organization in organization to populate org.
	// +kubebuilder:validation:Optional
	OrgSelector *v1.Selector `json:"orgSelector,omitempty" tf:"-"`

	// The router group GUID, which can be retrieved via the cloudfoundry_router_group data resource. You would need to provide this when creating a shared domain for TCP routes.
	RouterGroup *string `json:"routerGroup,omitempty" tf:"router_group,omitempty"`

	// Sub-domain part of full domain name. If specified the domain argument needs to be provided and the name will be computed.
	SubDomain *string `json:"subDomain,omitempty" tf:"sub_domain,omitempty"`
}

type DomainObservation struct {

	// Domain part of full domain name. If specified the sub_domain argument needs to be provided and the name will be computed.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// The GUID of the domain.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Flag that sets the domain as an internal domain. Internal domains are used for internal app to app networking only. Defaults to "false". Only works on shared domain.
	// Flag that sets the domain as an internal domain. Internal domains are used for internal app to app networking only.
	Internal *bool `json:"internal,omitempty" tf:"internal,omitempty"`

	// Full name of domain. If specified then the sub_domain and domain attributes will be computed from the name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the Org that owns this domain. If specified, this resource will provision a private domain. By default, the provisioned domain is a public (shared) domain.
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// The router group GUID, which can be retrieved via the cloudfoundry_router_group data resource. You would need to provide this when creating a shared domain for TCP routes.
	RouterGroup *string `json:"routerGroup,omitempty" tf:"router_group,omitempty"`

	RouterType *string `json:"routerType,omitempty" tf:"router_type,omitempty"`

	// Sub-domain part of full domain name. If specified the domain argument needs to be provided and the name will be computed.
	SubDomain *string `json:"subDomain,omitempty" tf:"sub_domain,omitempty"`
}

type DomainParameters struct {

	// Domain part of full domain name. If specified the sub_domain argument needs to be provided and the name will be computed.
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// Flag that sets the domain as an internal domain. Internal domains are used for internal app to app networking only. Defaults to "false". Only works on shared domain.
	// Flag that sets the domain as an internal domain. Internal domains are used for internal app to app networking only.
	// +kubebuilder:validation:Optional
	Internal *bool `json:"internal,omitempty" tf:"internal,omitempty"`

	// Full name of domain. If specified then the sub_domain and domain attributes will be computed from the name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the Org that owns this domain. If specified, this resource will provision a private domain. By default, the provisioned domain is a public (shared) domain.
	// +crossplane:generate:reference:type=github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/apis/organization/v1alpha1.Organization
	// +crossplane:generate:reference:extractor=github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/config.ExternalID()
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Reference to a Organization in organization to populate org.
	// +kubebuilder:validation:Optional
	OrgRef *v1.Reference `json:"orgRef,omitempty" tf:"-"`

	// Selector for a Organization in organization to populate org.
	// +kubebuilder:validation:Optional
	OrgSelector *v1.Selector `json:"orgSelector,omitempty" tf:"-"`

	// The router group GUID, which can be retrieved via the cloudfoundry_router_group data resource. You would need to provide this when creating a shared domain for TCP routes.
	// +kubebuilder:validation:Optional
	RouterGroup *string `json:"routerGroup,omitempty" tf:"router_group,omitempty"`

	// Sub-domain part of full domain name. If specified the domain argument needs to be provided and the name will be computed.
	// +kubebuilder:validation:Optional
	SubDomain *string `json:"subDomain,omitempty" tf:"sub_domain,omitempty"`
}

// DomainSpec defines the desired state of Domain
type DomainSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DomainParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DomainInitParameters `json:"initProvider,omitempty"`
}

// DomainStatus defines the observed state of Domain.
type DomainStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DomainObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Domain is the Schema for the Domains API. Provides a Cloud Foundry Domain resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudfoundry}
type Domain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DomainSpec   `json:"spec"`
	Status            DomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DomainList contains a list of Domains
type DomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Domain `json:"items"`
}

// Repository type metadata.
var (
	Domain_Kind             = "Domain"
	Domain_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Domain_Kind}.String()
	Domain_KindAPIVersion   = Domain_Kind + "." + CRDGroupVersion.String()
	Domain_GroupVersionKind = CRDGroupVersion.WithKind(Domain_Kind)
)

func init() {
	SchemeBuilder.Register(&Domain{}, &DomainList{})
}
