// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2023 SAP SE.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *App) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Domain) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PrivateDomainAccess) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Quota) Hub() {}
