/*
Copyright 2023 SAP SE.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/apis/resources/v1alpha1"
	v1alpha2 "github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/apis/resources/v1alpha2"
	config "github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/config"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this App.
func (mg *App) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Routes); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Routes[i3].Route),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.ForProvider.Routes[i3].RouteRef,
			Selector:     mg.Spec.ForProvider.Routes[i3].RouteSelector,
			To: reference.To{
				List:    &v1alpha1.RouteList{},
				Managed: &v1alpha1.Route{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Routes[i3].Route")
		}
		mg.Spec.ForProvider.Routes[i3].Route = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Routes[i3].RouteRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.ServiceBindings); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServiceBindings[i3].ServiceInstance),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.ForProvider.ServiceBindings[i3].ServiceInstanceRef,
			Selector:     mg.Spec.ForProvider.ServiceBindings[i3].ServiceInstanceSelector,
			To: reference.To{
				List:    &v1alpha2.ServiceInstanceList{},
				Managed: &v1alpha2.ServiceInstance{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ServiceBindings[i3].ServiceInstance")
		}
		mg.Spec.ForProvider.ServiceBindings[i3].ServiceInstance = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ServiceBindings[i3].ServiceInstanceRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Routes); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Routes[i3].Route),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.InitProvider.Routes[i3].RouteRef,
			Selector:     mg.Spec.InitProvider.Routes[i3].RouteSelector,
			To: reference.To{
				List:    &v1alpha1.RouteList{},
				Managed: &v1alpha1.Route{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Routes[i3].Route")
		}
		mg.Spec.InitProvider.Routes[i3].Route = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Routes[i3].RouteRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ServiceBindings); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServiceBindings[i3].ServiceInstance),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.InitProvider.ServiceBindings[i3].ServiceInstanceRef,
			Selector:     mg.Spec.InitProvider.ServiceBindings[i3].ServiceInstanceSelector,
			To: reference.To{
				List:    &v1alpha2.ServiceInstanceList{},
				Managed: &v1alpha2.ServiceInstance{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ServiceBindings[i3].ServiceInstance")
		}
		mg.Spec.InitProvider.ServiceBindings[i3].ServiceInstance = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ServiceBindings[i3].ServiceInstanceRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Domain.
func (mg *Domain) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Org),
		Extract:      config.ExternalID(),
		Reference:    mg.Spec.ForProvider.OrgRef,
		Selector:     mg.Spec.ForProvider.OrgSelector,
		To: reference.To{
			List:    &v1alpha2.OrgList{},
			Managed: &v1alpha2.Org{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Org")
	}
	mg.Spec.ForProvider.Org = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Org),
		Extract:      config.ExternalID(),
		Reference:    mg.Spec.InitProvider.OrgRef,
		Selector:     mg.Spec.InitProvider.OrgSelector,
		To: reference.To{
			List:    &v1alpha2.OrgList{},
			Managed: &v1alpha2.Org{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Org")
	}
	mg.Spec.InitProvider.Org = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.OrgRef = rsp.ResolvedReference

	return nil
}
