// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2023 SAP SE.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PrivateDomainAccessInitParameters struct {

	// The GUID of private domain.
	// +crossplane:generate:reference:type=Domain
	// +crossplane:generate:reference:refFieldName=DomainRef
	// +crossplane:generate:reference:selectorFieldName=DomainSelector
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// Reference to a Domain to populate domain.
	// +kubebuilder:validation:Optional
	DomainRef *v1.Reference `json:"domainRef,omitempty" tf:"-"`

	// Selector for a Domain to populate domain.
	// +kubebuilder:validation:Optional
	DomainSelector *v1.Selector `json:"domainSelector,omitempty" tf:"-"`

	// The GUID of the organization.
	// +crossplane:generate:reference:type=github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/apis/organization/v1alpha1.Organization
	// +crossplane:generate:reference:extractor=github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/config.ExternalID()
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Reference to a Organization in organization to populate org.
	// +kubebuilder:validation:Optional
	OrgRef *v1.Reference `json:"orgRef,omitempty" tf:"-"`

	// Selector for a Organization in organization to populate org.
	// +kubebuilder:validation:Optional
	OrgSelector *v1.Selector `json:"orgSelector,omitempty" tf:"-"`
}

type PrivateDomainAccessObservation struct {

	// The GUID of private domain.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The GUID of the organization.
	Org *string `json:"org,omitempty" tf:"org,omitempty"`
}

type PrivateDomainAccessParameters struct {

	// The GUID of private domain.
	// +crossplane:generate:reference:type=Domain
	// +crossplane:generate:reference:refFieldName=DomainRef
	// +crossplane:generate:reference:selectorFieldName=DomainSelector
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// Reference to a Domain to populate domain.
	// +kubebuilder:validation:Optional
	DomainRef *v1.Reference `json:"domainRef,omitempty" tf:"-"`

	// Selector for a Domain to populate domain.
	// +kubebuilder:validation:Optional
	DomainSelector *v1.Selector `json:"domainSelector,omitempty" tf:"-"`

	// The GUID of the organization.
	// +crossplane:generate:reference:type=github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/apis/organization/v1alpha1.Organization
	// +crossplane:generate:reference:extractor=github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/config.ExternalID()
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Reference to a Organization in organization to populate org.
	// +kubebuilder:validation:Optional
	OrgRef *v1.Reference `json:"orgRef,omitempty" tf:"-"`

	// Selector for a Organization in organization to populate org.
	// +kubebuilder:validation:Optional
	OrgSelector *v1.Selector `json:"orgSelector,omitempty" tf:"-"`
}

// PrivateDomainAccessSpec defines the desired state of PrivateDomainAccess
type PrivateDomainAccessSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PrivateDomainAccessParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PrivateDomainAccessInitParameters `json:"initProvider,omitempty"`
}

// PrivateDomainAccessStatus defines the observed state of PrivateDomainAccess.
type PrivateDomainAccessStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PrivateDomainAccessObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PrivateDomainAccess is the Schema for the PrivateDomainAccesss API. Provides a Cloud Foundry private domain access resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudfoundry}
type PrivateDomainAccess struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              PrivateDomainAccessSpec   `json:"spec"`
	Status            PrivateDomainAccessStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PrivateDomainAccessList contains a list of PrivateDomainAccesss
type PrivateDomainAccessList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PrivateDomainAccess `json:"items"`
}

// Repository type metadata.
var (
	PrivateDomainAccess_Kind             = "PrivateDomainAccess"
	PrivateDomainAccess_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PrivateDomainAccess_Kind}.String()
	PrivateDomainAccess_KindAPIVersion   = PrivateDomainAccess_Kind + "." + CRDGroupVersion.String()
	PrivateDomainAccess_GroupVersionKind = CRDGroupVersion.WithKind(PrivateDomainAccess_Kind)
)

func init() {
	SchemeBuilder.Register(&PrivateDomainAccess{}, &PrivateDomainAccessList{})
}
