apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: Quota
metadata:
  annotations:
    meta.upbound.io/example-id: cloudfoundry/v1alpha1/quota
  labels:
    testing.upbound.io/example-name: 10g
  name: 10g
spec:
  forProvider:
    allowPaidServicePlans: false
    instanceMemory: 512
    name: 10g
    orgSelector:
      matchLabels:
        testing.upbound.io/example-name: myorg
    totalAppInstances: 10
    totalMemory: 10240
    totalRoutes: 5
    totalServices: 20
