general:
  buildTool: 'golang'

  vaultAppRoleTokenCredentialsId: 'vault-approle-role-id-2442-20056'
  vaultAppRoleSecretTokenCredentialsId: 'vault-approle-secret-id-accessor-2442-20056'
  vaultPipelineName: 'PIPELINE-20056'

  repository: &REPOSITORY_NAME 'crossplane-provider-cloudfoundry'

  crossplane:
    targetOCIRegistry: deploy-releases-hyperspace-docker.common.cdn.repositories.cloud.sap

stages:
  Central Build:
    kanikoExecute: true

steps:
  artifactPrepareVersion:
    versioningType: library
  kanikoExecute:
    containerImageName: 'crossplane-provider-cloudfoundry'
    containerMultiImageBuild: true
    containerMultiImageBuildImages:
      'crossplane/provider-cloudfoundry': 'cluster/images/crossplane-provider-cloudfoundry/Dockerfile'
      'crossplane/provider-cloudfoundry-controller': 'cluster/images/crossplane-provider-cloudfoundry-controller/Dockerfile'
    buildOptions:
      - '--skip-unused-stages'
      - '--build-arg=BUILDENV=piper'
      - '--build-arg=BUILD_TIMESTAMP'
      - '--build-arg=GIT_COMMIT'
      - '--build-arg=TERRAFORM_VERSION=1.5.4'
      - '--build-arg=TERRAFORM_PROVIDER_SOURCE=cloudfoundry/cloudfoundry'
      - '--build-arg=TERRAFORM_PROVIDER_REPO=https://github.com/cloudfoundry/terraform-provider-cloudfoundry'
      - '--build-arg=TERRAFORM_PROVIDER_VERSION=1.1.0'
      - '--build-arg=TERRAFORM_PROVIDER_DOWNLOAD_NAME=terraform-provider-cloudfoundry'
      - '--build-arg=TERRAFORM_NATIVE_PROVIDER_BINARY=terraform-provider-cloudfoundry_1.1.0_linux_amd64'
  sapCumulusUpload:
    pipelineId: 'bfadeee2-2307-43a9-869d-5c44b9d83080'
  dockerExecute:
    dockerImage: 'debian:stable'
  golangBuild:
    dockerImage: &GOLANG_BUILDER 'golang:1.23'
    output: provider
    packages:
      - './cmd/provider/main.go'
    runTests: true
  # whitesourceExecuteScan: false
    # dockerImage: *GOLANG_BUILDER
    # whitesourceProductName: 'DIST - crossplane-provider-cloudfoundry'
    # whitesourceProductToken: 'a5eb05e7ad5b464cbe097f08b6329a54f5c91b30806348c8aa936beb47607099'
  checkmarxExecuteScan:
    projectName: *REPOSITORY_NAME
