resources:
  - org:
      name: my-manual-org
      managementPolicies: [Observe]
  - space: 
      name: .*
      orgRef: my-manual-org
      managementPolicies: [Observe]    
  - spaceMembers:
      roleType: .*
      spaceRef: manual-space
      managementPolicies: [Observe]
  - orgMembers:
      roleType: .*
      orgRef: my-manual-org
      managementPolicies: [Observe]
  - serviceInstance:
      name: .*
      spaceRef: manual-space
      type: managed
      managementPolicies: [Observe]
  - serviceInstance:
      name: .*
      spaceRef: manual-space
      type: user-provided
      managementPolicies: [Observe]
providerConfigRef:
  name: default
  namespace: default
