---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: Organization
metadata:
  namespace: default
  name: my-org
  annotations:
    crossplane.io/external-name: cf-dev
spec:
  forProvider: {}
