---
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Route
metadata:
  name: my-route
spec:
  forProvider:
    domainRef:
      name: my-domain
      policy:
        resolve: Always
    hostname: hello-cf
    spaceRef:
      name: my-space
      policy:
        resolve: Always