
# current: external-data
---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: ServiceInstance
metadata:
  name: my-service-instance-v1
  annotations:
    crossplane.io/external-data: |
      {
        "service_plan": {
          "offering": "auditlog-management",
          "plan": "default"
        }
      }
spec:
  forProvider:
    name: my-audit-log
    spaceRef: 
      name: my-space
      policy:
        resolve: Always

---
# CR to create a managed ServiceInstance
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: ServiceInstance
metadata:
  name: my-service-instance-v2
spec:
  forProvider:
    type: managed
    name: my-application-log-2
    spaceRef: 
      name: my-space
      policy: 
        resolve: Always
    servicePlan:
      offering: application-logs
      plan: lite
    jsonParams: |
      {
        "foo": "bar"
      }
    paramsSecretRef:
      name: secretParameters
      namespace: default
