---
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: SpaceQuota
metadata:
  name: my-space-quota
spec:
  forProvider:
    name: test-quota
    orgRef:
      name: my-org
    allowPaidServicePlans: false
    spacesRefs:
      - name: my-space
