apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: Org
metadata:
  namespace: default
  name: my-org
  annotations:
    crossplane.io/external-name: cf-dev
spec:
  forProvider:
    name: cf-dev

---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: Space
metadata:
  namespace: default
  name: my-space
spec:
  forProvider:
    allowSsh: true
    name: space-dev-x
    orgRef:
      name: my-org
      policy:
        resolve: Always

---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: SpaceMembers
metadata:
  namespace: default
  name: my-space-developers
spec:
  forProvider:
    roleType: Developers
    spaceRef:
      name: my-space
      policy:
        resolve: Always
    members:
    - username: 2@sap.com
    - username: 1@sap.com
    - username: dl_65faab09346a9101347c1723@global.corp.sap
    enforcementPolicy: Strict
