apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: Organization
metadata:
  namespace: default
  name: my-org
  annotations:
    crossplane.io/external-name: cf-dev
spec:
  forProvider: {}

---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: Space
metadata:
  namespace: default
  name: my-space
spec:
  forProvider:
    allowSsh: true
    name: space-dev
    orgRef:
      name: my-org
      policy:
        resolve: Always

---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: SpaceMembers
metadata:
  namespace: default
  name: my-space-developers
spec:
  forProvider:
    roleType: Developers
    spaceRef: 
      name: my-space
      policy:
        resolve: Always
    members:
    - username: cloudorchestrator@sap.com
    - username: daniel.lou@sap.com
    - username: thomas.hertz@sap.com
    - username: cesar.andres@sap.com
    - username: mirza@groups.sap.com
    enforcementPolicy: Strict