---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha1
kind: SpaceUsers
metadata:
  name: my-space-users
spec:
  forProvider:
    developers:
    - "2@sap.com"
    - "1@sap.com"
    spaceRef:
      name: my-space
      policy:
        resolve: Always
