---
# CR to create a managed ServiceInstance
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceInstance
metadata:
  name: my-service-instance
spec:
  forProvider:
    type: managed
    name: my-service-instance
    spaceRef: 
      name: my-space
      policy: 
        resolve: Always
    servicePlan:
      offering: destination
      plan: lite
    # tags are applied to the instance and surfaced in apps' VCAP_SERVICES.
    # Omitting this field or setting it to [] results in no tags.
    tags:
      - prod
      - eu-central
