---
apiVersion: v1
kind: Secret
metadata:
  name: my-credentials
  namespace: default
type: Opaque
stringData:
  login: |
    {
      "username": "admin",
      "password": "secret"
    }
  config: |
    {
      "database": {
        "host": "localhost",
        "port": 5432
      }
    }

---
# UPS with service credentials from a secret ref
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceInstance
metadata:
  name: my-ups
spec:
  forProvider:
    type: user-provided
    name: my-ups
    routeServiceUrl: https://my-route-service.example.com
    syslogDrainUrl: syslog-tls://example.log-aggregator.com:6514
    spaceRef: 
      name: my-space
      policy:
        resolve: Always
    credentialsSecretRef: 
        name: my-credentials
        namespace: default

