---
apiVersion: v1
kind: Secret
metadata:
  name: xsuaa-parameters
  namespace: crossplane-system
type: Opaque
stringData:
  xsappname: app-with-secret-json
  description: secret java application
  tenant-mode: shared
---

# managed service instance with parameter from a secret ref
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceInstance
metadata:
  name: my-xsuaa-secret-ref
spec:
  forProvider:
    type: managed
    name: my-xsuaa-secret-ref
    spaceRef: 
      name: my-space
    servicePlan:
      offering: xsuaa
      plan: application
    paramsSecretRef:
      name: xsuaa-parameters
      namespace: crossplane-system