apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane:provider:btp-cloudfoundry-provider-locallyrun:system
rules:
- apiGroups:
  - cloudfoundry.btp.orchestrate.cloud.sap
  resources:
  - providerconfigs
  - providerconfigs/status
  - organizations
  - orgs
  - orgmembers
  - spaces
  - spacemembers
  - spaceusers
  - serviceinstances
  - servicekeys
  - ups
  - apps
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create