# xInstance sets up a BTP subaccount with cloud foundry components for a hypothetical DwC instance
# Uses xOrg and xSpace compositions
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xinstances.composition-example.cloud.sap
spec:
  writeConnectionSecretsToNamespace: default
  compositeTypeRef:
    apiVersion: composition-example.cloud.sap/v1alpha1
    kind: xInstance
  patchSets:
    - name: org
      patches:
      - toFieldPath: spec.parameters.org
        type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: spec.parameters.project
            - fromFieldPath: spec.parameters.region
          strategy: string
          string:
            fmt: "%s-%s-%s"

  resources:
    # (btp-account-provider) set up subaccount and cf environment
    - name: xorg
      base: 
        apiVersion: composition-example.cloud.sap/v1alpha1
        kind: xOrg
        metadata:
          name: PATCH_ME
        spec:
          parameters:
            globalaccount: PATCH_ME
            region: PATCH_ME
      patches:
      - toFieldPath: metadata.name
        type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: spec.parameters.project
            - fromFieldPath: spec.parameters.region
          strategy: string
          string:
            fmt: "%s-%s-%s"
      - fromFieldPath: spec.parameters.globalaccount
      - fromFieldPath: spec.parameters.region

    # (btp-cloudfoundry-provider) create and config cf spaces 
    - name: xspace-dev 
      base:  
        apiVersion: composition-example.cloud.sap/v1alpha1
        kind: xSpace
        metadata:
          name: PATCH_ME
        spec:
          parameters:
            org: PATCH_ME
            stage: dev
      patches:
      - toFieldPath: metadata.name
        type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: spec.parameters.project
            - fromFieldPath: spec.parameters.region
          strategy: string
          string:
            fmt: "%s-%s-dev-%s"
      - type: PatchSet
        patchSetName: org 

    - name: xspace-test 
      base:  
        apiVersion: composition-example.cloud.sap/v1alpha1
        kind: xSpace
        metadata:
          name: PATCH_ME
        spec:
          parameters:
            org: PATCH_ME
            stage: test
      patches:
      - toFieldPath: metadata.name
        type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: spec.parameters.project
            - fromFieldPath: spec.parameters.region
          strategy: string
          string:
            fmt: "%s-%s-test-%s"
      - type: PatchSet
        patchSetName: org 

    - name: xspace-prod 
      base:  
        apiVersion: composition-example.cloud.sap/v1alpha1
        kind: xSpace
        metadata:
          name: PATCH_ME
        spec:
          parameters:
            org: PATCH_ME
            stage: prod
      patches:
      - toFieldPath: metadata.name
        type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: metadata.name
            - fromFieldPath: spec.parameters.project
            - fromFieldPath: spec.parameters.region
          strategy: string
          string:
            fmt: "%s-%s-prod-%s"
      - type: PatchSet
        patchSetName: org 
