# xSpace creates and config a cloudfoundry space for dwc orbit 
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xspaces.composition-example.cloud.sap
spec:
  group: composition-example.cloud.sap
  names:
    kind: xSpace
    plural: xspaces
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  org:
                    description: org name 
                    type: string 
                  stage:
                    description: project stage 
                    enum:
                      - "dev"
                      - "test"
                      - "prod"
                    type: string 
                    default: dev
                required:
                  - org
            required:
              - parameters
          status:
            type: object
            properties:
              id:
                description: id of the cf space
                type: string