---
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: App
metadata:
  namespace: default
  name: my-app
spec:
  forProvider:
    spaceRef:
      name: my-space 
    name: my-app-test
    lifecycle: docker
    docker:
      image: loud/hello_co:latest
    routes:
      - routeRef:
          name: my-cfapps-route
    processes:
      - type: web
        health-check-type: http
        health-check-http-endpoint: "/"
  
---
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: App
metadata:
  namespace: default
  name: my-app-2
spec:
  forProvider:
    spaceRef:
      name: my-space 
    name: my-app-1234
    lifecycle: docker
    docker:
      image: loud/hello_co:latest
    routes:
      - routeRef:
          name: my-route
    processes:
      - type: web
        health-check-type: http
        health-check-http-endpoint: "/"
