apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Mta
metadata:
  name: test-mta-philipp
  namespace: default
spec:
  forProvider:
    namespace: default
    space: 23f3f9b5-27bf-41ad-949c-50e45e4e63d6
    blueGreenDeploy: true
    abortOnError: false
    file:
      url: https://common.repositories.cloud.sap/deploy-releases-hyperspace-maven/com/sap/hyperspace/bookshkop/1.0.0-20250505070353+b9237f2c2645b881aec11c0493b1c47ad2639925/bookshkop-1.0.0-20250505070353+b9237f2c2645b881aec11c0493b1c47ad2639925.mtar
      credentialsSecretRef:
        name: artifactory-credentials-secret
        namespace: default
    modules:
      - bookshkop-srv-module2
      - bookshkop-srv
    deleteServices: true
    extension: |
      _schema-version: 3.3.0
      extends: bookshkop
      ID: bookshkop.extension
      modules:
        - name: bookshkop-srv
          parameters:
            instances: 3
            memory: 512M
        - name: bookshkop-srv-module2
          parameters:
            instances: 1
