apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Mta
metadata:
  name: test-mta7
  namespace: default
spec:
  forProvider:
    namespace: default
    space: spaceid
    blueGreenDeploy: true
    abortOnError: true
    versionRule: ALL
    modules:
      - bookshkop-srv
      - bookshkop-srv-module2
    file:
      url: <url>
      credentialsSecretRef:
      name: artifactory-credentials-secret
      namespace: default


