---
apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: Organization
metadata:
  namespace: default
  name: my-org
spec:
  managementPolicies: ["Observe"]
  forProvider: 
    name: complex-org-cf
  providerConfigRef:
    name: default

