apiVersion: cloudfoundry.crossplane.io/v1alpha1
kind: ServiceRouteBinding
metadata:
  name: test-sr-binding
spec:
  providerConfigRef:
    name: default
  forProvider:
    route_service_url: https://my-route-service.example.com # falls erforderlich
    relationships:
      route:
        guid: 12345678-1234-1234-1234-123456789012
      service_instance:
        guid: 87654321-4321-4321-4321-210987654321
    links:
      self:
        href: https://api.cf.example.com/v3/service_route_bindings/dummy # Platzhalter