apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: Org
metadata:
  namespace: default
  name: my-org
  annotations:
    crossplane.io/external-name: cf-dev
spec:
  forProvider:
    name: cf-dev

---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: Space
metadata:
  namespace: default
  name: my-space
spec:
  forProvider:
    allowSsh: true
    name: space-app
    orgRef:
      name: my-org
      policy:
        resolve: Always

---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: SpaceRole
metadata:
  namespace: default
  name: my-space-developer
spec:
  forProvider:
    type: Developer
    spaceRef:
      name: my-space
    username: 5@global.corp.sap
    origin: sap.ids

---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: SpaceRole
metadata:
  namespace: default
  name: my-space-developer-daniel
spec:
  forProvider:
    type: Developer
    spaceRef:
      name: my-space
    username: 1@sap.com
    origin: sap.ids
