---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: SpaceRole
metadata:
  namespace: default
  name: my-space-auditor
spec:
  forProvider:
    type: Auditor
    spaceRef:
      name: my-space
    username: lasse.friedrich@sap.com
    origin: sap.ids

---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: SpaceRole
metadata:
  namespace: default
  name: my-space-developer-daniel
spec:
  forProvider:
    type: Developer
    spaceRef:
      name: my-space
    username: daniel.lou@sap.com
    origin: sap.ids

---
apiVersion: cloudfoundry.btp.orchestrate.cloud.sap/v1alpha2
kind: SpaceRole
metadata:
  namespace: default
  name: my-space-developer
spec:
  forProvider:
    type: Developer
    spaceRef:
      name: my-space
    username: dl_673efb6870d04101363fc6b3@global.corp.sap
    origin: sap.ids