package main

import (
	_ "github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/org"
	_ "github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/orgrole"
	"github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/resources"
	_ "github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/serviceinstance"
	_ "github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/space"
	"github.com/SAP/crossplane-provider-cloudfoundry/internal/exporttool/cli"
	"github.com/SAP/crossplane-provider-cloudfoundry/internal/exporttool/cli/configparam"
	"github.com/SAP/crossplane-provider-cloudfoundry/internal/exporttool/cli/export"
)

const (
	shortName      = "cf"
	observedSystem = "Cloud Foundry"
)

var (
	apiUrlParam = configparam.String("apiUrl", "URL of the Cloud Foundry API").
			WithShortName("a").
			WithFlagName("apiUrl").
			WithEnvVarName("API_URL").
			WithExample("https://api.cf.enterprise.com")
	usernameParam = configparam.String("username", "Username at the Cloud Foundry API").
			WithShortName("u").
			WithFlagName("username").
			WithEnvVarName("USERNAME")
	passwordParam = configparam.SensitiveString("password", "Password at the Cloud Foundry API").
			WithShortName("p").
			WithFlagName("password").
			WithEnvVarName("PASSWORD")
	useCfLoginMethod = configparam.Bool("use-cf-login", "Reuse the login config generated by 'cf login' command").
				WithEnvVarName("USE_CF_LOGIN")
	resolveRefencesParam = configparam.Bool("resolve-references", "Resolve inter-resource references").
				WithShortName("r").
				WithEnvVarName("RESOLVE_REFERENCES")
)

func main() {
	cli.Configuration.ShortName = shortName
	cli.Configuration.ObservedSystem = observedSystem
	export.SetCommand(exportCmd)
	export.AddConfigParams(
		apiUrlParam,
		usernameParam,
		passwordParam,
		useCfLoginMethod,
		resolveRefencesParam,
	)
	export.AddConfigParams(resources.ConfigParams()...)
	export.AddResourceKinds(resources.KindNames()...)
	cli.Execute()
}
