package main

import (
	"fmt"

	_ "github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/org"
	_ "github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/orgrole"
	"github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/resources"
	_ "github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/serviceinstance"
	_ "github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/space"
	_ "github.com/SAP/crossplane-provider-cloudfoundry/cmd/exporter/cf/spacerole"

	"github.com/SAP/xp-clifford/cli"
	"github.com/SAP/xp-clifford/cli/configparam"
	"github.com/SAP/xp-clifford/cli/export"
)

var (
	ShortName      = "cf-exporter"
	observedSystem = "Cloud Foundry"
)

var (
	apiUrlParam = configparam.String("apiUrl", "URL of the Cloud Foundry API").
			WithShortName("a").
			WithFlagName("apiUrl").
			WithEnvVarName("API_URL").
			WithExample("https://api.cf.enterprise.com")
	usernameParam = configparam.String("username", "Username at the Cloud Foundry API").
			WithShortName("u").
			WithFlagName("username").
			WithEnvVarName("USERNAME")
	passwordParam = configparam.SensitiveString("password", "Password at the Cloud Foundry API").
			WithShortName("p").
			WithFlagName("password").
			WithEnvVarName("PASSWORD")
	useCfLoginMethod = configparam.Bool("use-cf-login", "Reuse the login config generated by 'cf login' command").
				WithEnvVarName("USE_CF_LOGIN")
	resolveRefencesParam = configparam.Bool("resolve-references", "Resolve inter-resource references").
				WithShortName("r").
				WithEnvVarName("RESOLVE_REFERENCES")
)

type cliConfig struct {
	cli.DefaultConfiguratorCLI
}

var _ cli.ConfiguratorCLI = cliConfig{}

func (c cliConfig) CommandUse(*cli.ConfigSchema) string {
	return fmt.Sprintf("%s [command] [flags...]", ShortName)
}

func main() {
	cli.Configuration.CLIConfiguration.ConfiguratorCLI = cliConfig{cli.DefaultConfiguratorCLI{}}
	cli.Configuration.ShortName = ShortName
	cli.Configuration.ObservedSystem = observedSystem
	export.SetCommand(exportCmd)
	export.AddConfigParams(
		apiUrlParam,
		usernameParam,
		passwordParam,
		useCfLoginMethod,
		resolveRefencesParam,
	)
	export.AddConfigParams(resources.ConfigParams()...)
	export.AddResourceKinds(resources.KindNames()...)
	cli.Execute()
}
