//go:build !ignore_autogenerated

/*
Copyright 2023 SAP SE.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKey) DeepCopyInto(out *ServiceKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKey.
func (in *ServiceKey) DeepCopy() *ServiceKey {
	if in == nil {
		return nil
	}
	out := new(ServiceKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKeyList) DeepCopyInto(out *ServiceKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKeyList.
func (in *ServiceKeyList) DeepCopy() *ServiceKeyList {
	if in == nil {
		return nil
	}
	out := new(ServiceKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKeyObservation) DeepCopyInto(out *ServiceKeyObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKeyObservation.
func (in *ServiceKeyObservation) DeepCopy() *ServiceKeyObservation {
	if in == nil {
		return nil
	}
	out := new(ServiceKeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKeyParameters) DeepCopyInto(out *ServiceKeyParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ParamsJSONSecretRef != nil {
		in, out := &in.ParamsJSONSecretRef, &out.ParamsJSONSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.ParamsSecretRef != nil {
		in, out := &in.ParamsSecretRef, &out.ParamsSecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.ServiceInstance != nil {
		in, out := &in.ServiceInstance, &out.ServiceInstance
		*out = new(string)
		**out = **in
	}
	if in.ServiceInstanceRef != nil {
		in, out := &in.ServiceInstanceRef, &out.ServiceInstanceRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceInstanceSelector != nil {
		in, out := &in.ServiceInstanceSelector, &out.ServiceInstanceSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKeyParameters.
func (in *ServiceKeyParameters) DeepCopy() *ServiceKeyParameters {
	if in == nil {
		return nil
	}
	out := new(ServiceKeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKeySpec) DeepCopyInto(out *ServiceKeySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKeySpec.
func (in *ServiceKeySpec) DeepCopy() *ServiceKeySpec {
	if in == nil {
		return nil
	}
	out := new(ServiceKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceKeyStatus) DeepCopyInto(out *ServiceKeyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceKeyStatus.
func (in *ServiceKeyStatus) DeepCopy() *ServiceKeyStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceKeyStatus)
	in.DeepCopyInto(out)
	return out
}
