/*
Copyright 2023 SAP SE.
*/

// Code generated by upjet. DO NOT EDIT.

// +kubebuilder:object:generate=true
// +groupName=cloudfoundry.crossplane.io
// +versionName=v1alpha1
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// Package type metadata.
const (
	CRDGroup   = "cloudfoundry.crossplane.io"
	CRDVersion = "v1alpha1"
)

var (
	// CRDGroupVersion is the API Group Version used to register the objects
	CRDGroupVersion = schema.GroupVersion{Group: CRDGroup, Version: CRDVersion}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

// addKnownTypes registers the types of this group version with the scheme.
func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(CRDGroupVersion,
		&App{},
		&AppList{},
		&Domain{},
		&DomainList{},
		&Organization{},
		&OrganizationList{},
		&OrgMembers{},
		&OrgMembersList{},
		&OrgQuota{},
		&OrgQuotaList{},
		&OrgRole{},
		&OrgRoleList{},
		&Route{},
		&RouteList{},
		&ServiceCredentialBinding{},
		&ServiceCredentialBindingList{},
		&ServiceInstance{},
		&ServiceInstanceList{},
		&ServiceRouteBinding{},
		&ServiceRouteBindingList{},
		&SpaceQuota{},
		&SpaceQuotaList{},
		&Space{},
		&SpaceList{},
		&SpaceMembers{},
		&SpaceMembersList{},
		&SpaceRole{},
		&SpaceRoleList{},
	)
	metav1.AddToGroupVersion(scheme, CRDGroupVersion)
	return nil
}
