/*
Copyright 2023 SAP SE
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SpaceObservation struct {

	// The GUID of the Space
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SpaceParameters struct {

	// Allows SSH to application containers via the CF CLI. Defaults to true.
	// +kubebuilder:validation:Optional
	AllowSSH *bool `json:"allowSsh,omitempty" tf:"allow_ssh,omitempty"`

	// Add annotations as described here.
	// Works only on cloud foundry with api >= v3.63.
	// +kubebuilder:validation:Optional
	Annotations map[string]*string `json:"annotations,omitempty" tf:"annotations,omitempty"`

	// List of running application security groups to apply to applications running within this space. Defaults to empty list.
	// +kubebuilder:validation:Optional
	Asgs []*string `json:"asgs,omitempty" tf:"asgs,omitempty"`

	// +kubebuilder:validation:Optional
	// Auditors []*string `json:"auditors,omitempty" tf:"auditors,omitempty"`

	// +kubebuilder:validation:Optional
	// Developers []*string `json:"developers,omitempty" tf:"developers,omitempty"`

	// (Experimental,Optional) The ID of the isolation segment to assign to the space. The segment must be entitled to the space's parent organization. If the isolation segment id is unspecified, then Cloud Foundry assigns the space to the org’s default isolation segment if any. Note that existing apps in the space will not run in a newly assigned isolation segment until they are restarted.
	// +kubebuilder:validation:Optional
	IsolationSegment *string `json:"isolationSegment,omitempty" tf:"isolation_segment,omitempty"`

	// Add labels as described here.
	// Works only on cloud foundry with api >= v3.63.
	// +kubebuilder:validation:Optional
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// +kubebuilder:validation:Optional
	// Managers []*string `json:"managers,omitempty" tf:"managers,omitempty"`

	// The name of the Space in Cloud Foundry.
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// The ID of the Org within which to create the space.
	// +crossplane:generate:reference:type=github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/apis/resources/v1alpha1.Organization
	// +crossplane:generate:reference:extractor=github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/apis/resources.ExternalID()
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Reference to a Organization in organization to populate org.
	// +kubebuilder:validation:Optional
	OrgRef *v1.Reference `json:"orgRef,omitempty" tf:"-"`

	// Selector for a Organization in organization to populate org.
	// +kubebuilder:validation:Optional
	OrgSelector *v1.Selector `json:"orgSelector,omitempty" tf:"-"`

	// The ID of the Space quota or plan defined for the owning Org. Specifying an empty string requests unassigns any space quota from the space. Defaults to empty string.
	// +kubebuilder:validation:Optional
	Quota *string `json:"quota,omitempty" tf:"quota,omitempty"`

	// List of staging application security groups to apply to applications being staged for this space. Defaults to empty list.
	// +kubebuilder:validation:Optional
	StagingAsgs []*string `json:"stagingAsgs,omitempty" tf:"staging_asgs,omitempty"`
}

// SpaceSpec defines the desired state of Space
type SpaceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SpaceParameters `json:"forProvider"`
}

// SpaceStatus defines the observed state of Space.
type SpaceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SpaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Space is the Schema for the Spaces API. Provides a Cloud Foundry Space resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudfoundry}
// +kubebuilder:deprecatedversion:warning="v1alpha1/Space is deprecated. Use v1alpha2/Space"
type Space struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SpaceSpec   `json:"spec"`
	Status            SpaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SpaceList contains a list of Spaces
type SpaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Space `json:"items"`
}

// Repository type metadata.
var (
	Space_Kind             = "Space"
	Space_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Space_Kind}.String()
	Space_KindAPIVersion   = Space_Kind + "." + CRDGroupVersion.String()
	Space_GroupVersionKind = CRDGroupVersion.WithKind(Space_Kind)
)

func init() {
	SchemeBuilder.Register(&Space{}, &SpaceList{})
}

// GetID returns ID of the underlying resource at provider
func (tr *Space) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}
