/*
Copyright 2022 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	resources "github.com/SAP/crossplane-provider-cloudfoundry/apis/resources"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this App.
func (mg *App) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SpaceReference.Space),
		Extract:      resources.ExternalID(),
		Reference:    mg.Spec.ForProvider.SpaceReference.SpaceRef,
		Selector:     mg.Spec.ForProvider.SpaceReference.SpaceSelector,
		To: reference.To{
			List:    &SpaceList{},
			Managed: &Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SpaceReference.Space")
	}
	mg.Spec.ForProvider.SpaceReference.Space = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SpaceReference.SpaceRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Routes); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Routes[i3].Route),
			Extract:      resources.CloudFoundryName(),
			Reference:    mg.Spec.ForProvider.Routes[i3].RouteRef,
			Selector:     mg.Spec.ForProvider.Routes[i3].RouteSelector,
			To: reference.To{
				List:    &RouteList{},
				Managed: &Route{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Routes[i3].Route")
		}
		mg.Spec.ForProvider.Routes[i3].Route = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Routes[i3].RouteRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Services); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Services[i3].Name),
			Extract:      resources.CloudFoundryName(),
			Reference:    mg.Spec.ForProvider.Services[i3].ServiceInstanceRef,
			Selector:     mg.Spec.ForProvider.Services[i3].ServiceInstanceSelector,
			To: reference.To{
				List:    &ServiceInstanceList{},
				Managed: &ServiceInstance{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Services[i3].Name")
		}
		mg.Spec.ForProvider.Services[i3].Name = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Services[i3].ServiceInstanceRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Domain.
func (mg *Domain) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgReference.Org),
		Extract:      resources.ExternalID(),
		Reference:    mg.Spec.ForProvider.OrgReference.OrgRef,
		Selector:     mg.Spec.ForProvider.OrgReference.OrgSelector,
		To: reference.To{
			List:    &OrganizationList{},
			Managed: &Organization{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgReference.Org")
	}
	mg.Spec.ForProvider.OrgReference.Org = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgReference.OrgRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this OrgMembers.
func (mg *OrgMembers) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgReference.Org),
		Extract:      resources.ExternalID(),
		Reference:    mg.Spec.ForProvider.OrgReference.OrgRef,
		Selector:     mg.Spec.ForProvider.OrgReference.OrgSelector,
		To: reference.To{
			List:    &OrganizationList{},
			Managed: &Organization{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgReference.Org")
	}
	mg.Spec.ForProvider.OrgReference.Org = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgReference.OrgRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this OrgRole.
func (mg *OrgRole) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgReference.Org),
		Extract:      resources.ExternalID(),
		Reference:    mg.Spec.ForProvider.OrgReference.OrgRef,
		Selector:     mg.Spec.ForProvider.OrgReference.OrgSelector,
		To: reference.To{
			List:    &OrganizationList{},
			Managed: &Organization{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgReference.Org")
	}
	mg.Spec.ForProvider.OrgReference.Org = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgReference.OrgRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Route.
func (mg *Route) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SpaceReference.Space),
		Extract:      resources.ExternalID(),
		Reference:    mg.Spec.ForProvider.SpaceReference.SpaceRef,
		Selector:     mg.Spec.ForProvider.SpaceReference.SpaceSelector,
		To: reference.To{
			List:    &SpaceList{},
			Managed: &Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SpaceReference.Space")
	}
	mg.Spec.ForProvider.SpaceReference.Space = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SpaceReference.SpaceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DomainReference.Domain),
		Extract:      resources.ExternalID(),
		Reference:    mg.Spec.ForProvider.DomainReference.DomainRef,
		Selector:     mg.Spec.ForProvider.DomainReference.DomainSelector,
		To: reference.To{
			List:    &DomainList{},
			Managed: &Domain{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DomainReference.Domain")
	}
	mg.Spec.ForProvider.DomainReference.Domain = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DomainReference.DomainRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ServiceCredentialBinding.
func (mg *ServiceCredentialBinding) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServiceInstance),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ServiceInstanceRef,
		Selector:     mg.Spec.ForProvider.ServiceInstanceSelector,
		To: reference.To{
			List:    &ServiceInstanceList{},
			Managed: &ServiceInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceInstance")
	}
	mg.Spec.ForProvider.ServiceInstance = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServiceInstanceRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.App),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.AppRef,
		Selector:     mg.Spec.ForProvider.AppSelector,
		To: reference.To{
			List:    &AppList{},
			Managed: &App{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.App")
	}
	mg.Spec.ForProvider.App = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AppRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ServiceInstance.
func (mg *ServiceInstance) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SpaceReference.Space),
		Extract:      resources.ExternalID(),
		Reference:    mg.Spec.ForProvider.SpaceReference.SpaceRef,
		Selector:     mg.Spec.ForProvider.SpaceReference.SpaceSelector,
		To: reference.To{
			List:    &SpaceList{},
			Managed: &Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SpaceReference.Space")
	}
	mg.Spec.ForProvider.SpaceReference.Space = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SpaceReference.SpaceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Space.
func (mg *Space) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgReference.Org),
		Extract:      resources.ExternalID(),
		Reference:    mg.Spec.ForProvider.OrgReference.OrgRef,
		Selector:     mg.Spec.ForProvider.OrgReference.OrgSelector,
		To: reference.To{
			List:    &OrganizationList{},
			Managed: &Organization{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgReference.Org")
	}
	mg.Spec.ForProvider.OrgReference.Org = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgReference.OrgRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SpaceMembers.
func (mg *SpaceMembers) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SpaceReference.Space),
		Extract:      resources.ExternalID(),
		Reference:    mg.Spec.ForProvider.SpaceReference.SpaceRef,
		Selector:     mg.Spec.ForProvider.SpaceReference.SpaceSelector,
		To: reference.To{
			List:    &SpaceList{},
			Managed: &Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SpaceReference.Space")
	}
	mg.Spec.ForProvider.SpaceReference.Space = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SpaceReference.SpaceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SpaceQuota.
func (mg *SpaceQuota) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Spaces),
		Extract:       resources.ExternalID(),
		References:    mg.Spec.ForProvider.SpacesRefs,
		Selector:      mg.Spec.ForProvider.SpacesSelector,
		To: reference.To{
			List:    &SpaceList{},
			Managed: &Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Spaces")
	}
	mg.Spec.ForProvider.Spaces = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.SpacesRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Spaces),
		Extract:       resources.ExternalID(),
		References:    mg.Spec.InitProvider.SpacesRefs,
		Selector:      mg.Spec.InitProvider.SpacesSelector,
		To: reference.To{
			List:    &SpaceList{},
			Managed: &Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Spaces")
	}
	mg.Spec.InitProvider.Spaces = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.SpacesRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this SpaceRole.
func (mg *SpaceRole) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SpaceReference.Space),
		Extract:      resources.ExternalID(),
		Reference:    mg.Spec.ForProvider.SpaceReference.SpaceRef,
		Selector:     mg.Spec.ForProvider.SpaceReference.SpaceSelector,
		To: reference.To{
			List:    &SpaceList{},
			Managed: &Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SpaceReference.Space")
	}
	mg.Spec.ForProvider.SpaceReference.Space = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SpaceReference.SpaceRef = rsp.ResolvedReference

	return nil
}
