/*
Copyright 2023 SAP SE.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha2 "github.tools.sap/cloud-orchestration/crossplane-provider-cloudfoundry/apis/resources/v1alpha2"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this OrgMembers.
func (mg *OrgMembers) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Org),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.OrgRef,
		Selector:     mg.Spec.ForProvider.OrgSelector,
		To: reference.To{
			List:    &v1alpha2.OrgList{},
			Managed: &v1alpha2.Org{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Org")
	}
	mg.Spec.ForProvider.Org = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Route.
func (mg *Route) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Space),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SpaceRef,
		Selector:     mg.Spec.ForProvider.SpaceSelector,
		To: reference.To{
			List:    &v1alpha2.SpaceList{},
			Managed: &v1alpha2.Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Space")
	}
	mg.Spec.ForProvider.Space = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SpaceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ServiceKey.
func (mg *ServiceKey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServiceInstance),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ServiceInstanceRef,
		Selector:     mg.Spec.ForProvider.ServiceInstanceSelector,
		To: reference.To{
			List:    &v1alpha2.ServiceInstanceList{},
			Managed: &v1alpha2.ServiceInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceInstance")
	}
	mg.Spec.ForProvider.ServiceInstance = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServiceInstanceRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Space.
func (mg *Space) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Org),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.OrgRef,
		Selector:     mg.Spec.ForProvider.OrgSelector,
		To: reference.To{
			List:    &v1alpha2.OrgList{},
			Managed: &v1alpha2.Org{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Org")
	}
	mg.Spec.ForProvider.Org = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SpaceMembers.
func (mg *SpaceMembers) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Space),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.SpaceRef,
		Selector:     mg.Spec.ForProvider.SpaceSelector,
		To: reference.To{
			List:    &v1alpha2.SpaceList{},
			Managed: &v1alpha2.Space{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Space")
	}
	mg.Spec.ForProvider.Space = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SpaceRef = rsp.ResolvedReference

	return nil
}
