on:
  pull_request:

jobs:
  build:
    name: Check nix flakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          check-outdated: false
