---
name: make reviewable

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  reviewable:
    uses: cloud-orchestration/.workflows/.github/workflows/make-reviewable.yml@v1.17.2
    secrets: inherit
    with:
      lintTimeout: 20
