---
name: make generate
on:
  repository_dispatch:
    types: [ make-generate-command ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  generate:
    uses: cloud-orchestration/.workflows/.github/workflows/make-generate-command.yaml@v1.17.2
    secrets: inherit
