# The on.pull_request pipeline runs on changes to a pull request. With this trigger, the pipeline never receives secrets from gh and the GITHUB_TOKEN is read only.
# Therefore, we can not run our e2e tests here, this needs to be done in an on.pull_request_target pipeline.
name: PullRequest Tests and Pre-Checks

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
    paths-ignore:
      - '*.md'

jobs:
  run-go-license-check:
    uses: ./.github/workflows/check-go-licenses.yaml

  run-reuse-license-check:
    uses: ./.github/workflows/reuse-scan.yaml

  run-unit-test:
    uses: ./.github/workflows/unit_test.yaml

  run-make-reviewable-and-check-diff:
    uses: ./.github/workflows/reviewable_check_diff.yaml