# This workflow will run make reviewable and make check-diff as checks

name: Reviewable&Check-Diff

on:
  workflow_dispatch:
  workflow_call:

env:
  GO_IMPORT_VERSION: 'v0.16.1'

jobs:
  reviewable-checkdiff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: '1.23'

    - name: Install go imports
      run: |
        cd /tmp
        go install golang.org/x/tools/cmd/goimports@${{ env.GO_IMPORT_VERSION }}

    - name: Make Reviewable
      run: make reviewable
      env:
        RUNNING_IN_CI: 'true'
    - name: Make Check-Diff
      run: make check-diff
